# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPT2016', '0003_auto_20160205_0820'),
        ('IPT2016', '0027_auto_20160201_0038'),
    ]

    operations = [
    ]
